name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'
  schedule:
    # @weekly (Sunday)
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { php_major_minor: "8.2", php_full_version: "8.2.7" }
          - { php_major_minor: "8.1", php_full_version: "8.1.20" }
          - { php_major_minor: "8.0", php_full_version: "8.0.29" }

    name: >-
      PHP ${{ matrix.php_full_version }}

    permissions:
      contents: read
      id-token: write

    concurrency:
      group: ${{ github.head_ref || github.run_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Docker GitHub Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: |
            ghcr.io/luislavena/hydrofoil-php
          tags: |
            type=raw,${{ matrix.php_full_version }}
            type=raw,${{ matrix.php_major_minor }}

      - name: Setup Docker BuildKit cache strategy
        uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/build-cache
          tag-prefix: php-${{ matrix.php_major_minor }}--

      - name: Build container images
        uses: depot/build-push-action@v1
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          context: docker/${{ matrix.php_major_minor }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

      # FIXME: re-enable testing before pushing
      # - name: Install Goss
      #   uses: e1himself/goss-installation-action@v1.1.0
      #   with:
      #     version: 'v0.3.20'

      # - name: Test Docker image
      #   run: dgoss run local-image:ci sleep infinity
      #   env:
      #     GOSS_FILE: docker/${{ matrix.php_major_minor }}/goss.yaml

      # - name: Push Docker images
      #   uses: docker/build-push-action@v3.2.0
      #   with:
      #     context: docker/${{ matrix.php_major_minor }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     platforms: |
      #       linux/amd64
      #     push: ${{ github.event_name != 'pull_request' }}
      #     cache-from: ${{ steps.cache.outputs.cache-from }}
      #     cache-to: ${{ steps.cache.outputs.cache-to }}
